services:
  typesense:
    image: typesense/typesense:30.2
    container_name: typesense
    volumes:
      - ./typesense-data:/data
    env_file:
      - .env
    expose:
      - "${TYPESENSE_PORT}"
    command: >
      --data-dir /data
      --api-key=${TYPESENSE_API_KEY}
      --enable-cors
    restart: unless-stopped

  airport-search:
    container_name: airport-search
    image: registry.gitlab.com/nakul-gupta/airport-search:latest
    build:
      context: ..
      dockerfile: backend/Dockerfile
    depends_on:
      - typesense
    env_file:
      - .env
    ports:
      - "3004:3004"
    restart: unless-stopped
