services:
  typesense:
    image: typesense/typesense:30.2
    container_name: typesense
    volumes:
      - ./typesense-data:/data
    env_file:
      - .env
    command: >
      --data-dir /data
      --api-key=${TYPESENSE_API_KEY}
      --enable-cors
    restart: unless-stopped

  airport-search:
    container_name: airport-search
    image: registry.gitlab.com/nakul-gupta/airport-search:latest
    depends_on:
      - typesense
    env_file:
      - .env
    ports:
      - "3004:3004"
    restart: unless-stopped
    volumes:
      - airport_search_frontend:/app/frontend # This handles the auto-copy

volumes:
  airport_search_frontend:
    driver: local
    driver_opts:
      type: none
      device: /var/www/airport-search/frontend
      o: bind
